# Generated by Django 3.1 on 2020-09-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['title'], 'verbose_name': 'Категория Меню', 'verbose_name_plural': 'Категории Меню'},
        ),
        migrations.AlterModelOptions(
            name='postscategory',
            options={'ordering': ['title'], 'verbose_name': 'Категория Поста', 'verbose_name_plural': 'Категории Поста'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-sort_id'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AddField(
            model_name='comment',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='sort_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='bonusactions',
            field=models.BooleanField(default=False, verbose_name='Акции'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_id',
            field=models.IntegerField(blank=True, verbose_name='Сортировка'),
        ),
    ]
