# Generated by Django 3.1 on 2020-09-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0002_auto_20200910_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
