# Generated by Django 3.1 on 2020-09-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0007_auto_20200916_2058'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
