# Generated by Django 3.1 on 2020-09-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0013_auto_20200926_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
