# Generated by Django 3.1 on 2020-11-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0016_auto_20200926_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quality',
            field=models.IntegerField(default=1),
        ),
    ]
